version: "3.9"

services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v5.28.0
    container_name: osrm-colombia
    restart: unless-stopped
    volumes:
      - ./osrm_resources/osrm_data:/data
    command: osrm-routed --algorithm mld /data/colombia/colombia-latest.osrm
    networks:
      - alfred-net

  alfred:
    build: .
    container_name: alfred-solver
    depends_on:
      - osrm
    env_file:
      - .env.docker
    volumes:
      - ./request:/app/request
      - ./output:/app/output
    networks:
      - alfred-net

networks:
  alfred-net:
    driver: bridge
