"""
issue_license.py — Issue a signed license file for a customer.

Usage:
    python license_tools/issue_license.py \\
        --customer "Acme Corp" \\
        --expires 2026-12-31 \\
        --out /path/to/acme_license.json \\
        [--key-id v1]

The license file is a JSON object with a cryptographic signature over the
payload fields (customer, expires, issued_at). The binary verifies this
signature on every run using the embedded public key.

Requires: license_tools/private_key.pem  (generated by generate_keys.py)
"""
import argparse
import base64
import getpass
import json
from datetime import date, datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key

_HERE     = Path(__file__).parent
_PRIV_PEM = _HERE / "private_key.pem"
_LOG_FILE = _HERE / "issued_licenses.log"


def _canonical_payload(customer: str, expires: str, issued_at: str) -> bytes:
    """Deterministic JSON bytes that are signed — sorted keys, no whitespace."""
    return json.dumps(
        {"customer": customer, "expires": expires, "issued_at": issued_at},
        sort_keys=True, separators=(",", ":"),
    ).encode()


def issue_license(customer: str, expires: str, out_path: Path, key_id: str = "") -> None:
    if not _PRIV_PEM.exists():
        print(f"ERROR: {_PRIV_PEM} not found. Run generate_keys.py first.")
        raise SystemExit(1)

    # Validate expires format
    try:
        datetime.strptime(expires, "%Y-%m-%d")
    except ValueError:
        print(f"ERROR: --expires must be YYYY-MM-DD, got: {expires!r}")
        raise SystemExit(1)

    # Validate customer
    customer = customer.strip()
    if not customer:
        print("ERROR: --customer must not be empty.")
        raise SystemExit(1)
    if not (2 <= len(customer) <= 100):
        print(f"ERROR: --customer must be between 2 and 100 characters, got {len(customer)}.")
        raise SystemExit(1)
    if not customer.isprintable():
        print("ERROR: --customer must contain only printable characters.")
        raise SystemExit(1)

    issued_at = date.today().isoformat()

    passphrase_str = getpass.getpass("Private key passphrase: ")
    try:
        private_key: Ed25519PrivateKey = load_pem_private_key(
            _PRIV_PEM.read_bytes(),
            password=passphrase_str.encode() if passphrase_str else None,
        )
    except Exception:
        print("ERROR: Failed to load private key. Wrong passphrase?")
        raise SystemExit(1)

    payload = _canonical_payload(customer, expires, issued_at)
    sig_bytes = private_key.sign(payload)
    signature = base64.b64encode(sig_bytes).decode()

    license_data = {
        "customer":  customer,
        "expires":   expires,
        "issued_at": issued_at,
        "signature": signature,
    }
    if key_id:
        license_data["key_id"] = key_id

    out_path.write_text(json.dumps(license_data, indent=2) + "\n")
    print(f"License issued for: {customer!r}")
    print(f"  Expires:   {expires}")
    print(f"  Issued at: {issued_at}")
    if key_id:
        print(f"  Key ID:    {key_id}")
    print(f"  Written to: {out_path}")

    # Audit log
    log_entry = (
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')} | "
        f"customer={customer!r} | expires={expires} | "
        f"issued_at={issued_at} | key_id={key_id!r} | out={out_path}\n"
    )
    try:
        with _LOG_FILE.open("a", encoding="utf-8") as lf:
            lf.write(log_entry)
    except Exception as e:
        print(f"WARNING: Could not write to audit log {_LOG_FILE}: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Issue a signed alfred_solver license.")
    parser.add_argument("--customer", required=True, help="Customer name (included in the license).")
    parser.add_argument("--expires",  required=True, help="Expiry date in YYYY-MM-DD format.")
    parser.add_argument("--out",      required=True, type=Path, help="Output path for the license JSON file.")
    parser.add_argument("--key-id",   default="",    help="Key version identifier to embed in the license (e.g. 'v1').")
    args = parser.parse_args()

    issue_license(args.customer, args.expires, args.out, key_id=args.key_id)


if __name__ == "__main__":
    main()
